AWSTemplateFormatVersion: '2010-09-09'
Description: Amplify Environment Creation via CloudFormation with Git Sync

Parameters:
  AppName:
    Type: String
    Description: The name of the Amplify application
    Default: kobashi-sample-amplify

  BranchName:
    Type: String
    Description: The branch to deploy
    Default: main

  GitHubRepo:
    Type: String
    Description: The GitHub repository URL
    Default: https://github.com/kobashi-yoshizumi/amplify_sample

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Repository: !Ref GitHubRepo
      OAuthToken: "{{resolve:secretsmanager:amplifyapp:SecretString:MyGitHubToken}}"
      AccessToken: "{{resolve:secretsmanager:amplifyapp:SecretString:MyGitHubAccessToken}}"
      Branches:
        - BranchName: !Ref BranchName
          BasicAuthConfig:
            EnableBasicAuth: false
          BuildSpec: |
            version: 1
            frontend:
              phases:
                preBuild:
                  commands:
                    - npm install
                build:
                  commands:
                    - npm run build
              artifacts:
                baseDirectory: build
                files:
                  - '**/*'
              cache:
                paths:
                  - node_modules/**/*

Outputs:
  AmplifyAppUrl:
    Description: URL of the Amplify Application
    Value: !GetAtt AmplifyApp.DefaultDomain
