AWSTemplateFormatVersion: '2010-09-09'
Description: AppSync API Configuration with Cognito Authentication

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: Existing Cognito User Pool ID
  AppSyncAPIName:
    Type: String
    Default: NewAppSyncAPI
    Description: Name of the AppSync API

Resources:
  AppSyncGraphQLAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref AppSyncAPIName
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        AwsRegion: !Ref "AWS::Region"
        UserPoolId: !Ref CognitoUserPoolId
        DefaultAction: ALLOW

  AppSyncGraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !Ref AppSyncGraphQLAPI
      Definition: |
        type Query {
          hello: String
        }

Outputs:
  AppSyncApiId:
    Description: The ID of the AppSync API
    Value: !Ref AppSyncGraphQLAPI

  AppSyncApiEndpoint:
    Description: The endpoint of the AppSync API
    Value: !GetAtt AppSyncGraphQLAPI.GraphQLUrl
