AWSTemplateFormatVersion: '2010-09-09'
Description: AppSync API Only

Parameters:
  CognitoUserPoolId:
    Type: String
  AppSyncAPIName:
    Type: String
    Default: kobashi-sample-appsync

Resources:
  AppSyncGraphQLAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref AppSyncAPIName
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        AwsRegion: !Ref AWS::Region
        UserPoolId: !Ref CognitoUserPoolId
        DefaultAction: ALLOW

Outputs:
  AppSyncApiId:
    Value: !Ref AppSyncGraphQLAPI
    Export:
      Name: AppSyncApiId-Kobashi
